apiVersion: apps/v1
kind: Deployment
metadata:
  name: klovercloud-integration-manager
  namespace: klovercloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klovercloud-integration-manager
  template:
    metadata:
      labels:
        app: klovercloud-integration-manager
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: app
          imagePullPolicy: Always
          image: quay.io/klovercloud/ci-integration-manager:v1.0.1
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
          envFrom:
            - configMapRef:
                name: klovercloud-integration-manager-envar-config
            - secretRef:
                name: klovercloud-mongo-secret
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
