apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: klovercloud-ci-core-rolebinding
  namespace: klovercloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ci-core-cluster-role
subjects:
  - kind: ServiceAccount
    name: klovercloud-ci-core-sa
    namespace: klovercloud