apiVersion: v1
kind: Service
metadata:
  name: klovercloud-ci-light-house-command
  namespace: klovercloud
  labels:
    app: klovercloud-ci-light-house-command
spec:
  ports:
    - name: http-rest
      port: 80
      targetPort: 8080
  selector:
    app: klovercloud-ci-light-house-command