apiVersion: v1
kind: Service
metadata:
  name: klovercloud-api-service
  namespace: klovercloud
  labels:
    app: klovercloud-api-service
spec:
  ports:
    - name: http-rest
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: klovercloud-api-service