apiVersion: apps/v1
kind: Deployment
metadata:
  name: klovercloud-api-service
  namespace: klovercloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klovercloud-api-service
  template:
    metadata:
      labels:
        app: klovercloud-api-service
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: app
          imagePullPolicy: Always
          image: quay.io/klovercloud/ci-api-service:v0.0.1-beta
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 66m
              memory: 256Mi
          envFrom:
            - configMapRef:
                name: klovercloud-api-service-envar-config
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
