apiVersion: v1
kind: Service
metadata:
  name: klovercloud-integration-manager
  namespace: klovercloud
  labels:
    app: klovercloud-integration-manager
spec:
  ports:
    - name: http-rest
      port: 80
      targetPort: 8080
  selector:
    app: klovercloud-integration-manager