apiVersion: v1
kind: ConfigMap
metadata:
  name: ci-console-config
  namespace: klovercloud
data:
  v1AuthEndpoint: "${securityUrl}"
  v1ApiEndPoint: "${apiServiceUrl}"
  v1ApiEndPointWS: "${webhookEventUrl}"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: klovercloud-ci-console
  namespace: klovercloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klovercloud-ci-console
  template:
    metadata:
      labels:
        app: klovercloud-ci-console
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: app
          imagePullPolicy: Always
          image: quay.io/klovercloud/ci-console:v0.0.1
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 66m
              memory: 256Mi
          envFrom:
            - configMapRef:
                name: ci-console-config
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: klovercloud-ci-console
  namespace: klovercloud
  labels:
    app: klovercloud-ci-console
spec:
  ports:
    - name: http-rest
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: klovercloud-ci-console
